export const UPDATE_ROLE = 'UPDATE_ROLE'; //existing
export const UPDATE_NEW_ROLE = 'UPDATE_NEW_ROLE'; //new additions
export const GET_ACCOUNT_HOLDERS_SUCCESS = 'GET_ACCOUNT_HOLDERS_SUCCESS';
export const GET_ASSOCIATED_SUCCESS = 'GET_ASSOCIATED_SUCCESS';
export const ADD_ACCOUNT_HOLDER = 'ADD_ACCOUNT_HOLDER';

export const ADD_FIELD = 'ADD_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';